//! The engine on the wire: the tee wrapper, the skip guards, and the servant that answers reverse
//! requests.
//!
//! Everything that decides *whether* there is something to measure lives here beside the launch
//! itself — the pinned artifact's path, the two CA conditions that make a successful prompt
//! evidence about the runtime's own CA injection rather than about an environment that already had
//! one, and the credential the profile references instead of containing. `WRAPPER` is the two-way
//! `tee` the launch goes through, and `servant` is what keeps a turn from hanging on a reverse
//! request the host registered no handler for.
//!
//! `one_turn_at_a_time` is here rather than in `turn` because it is about the machine and the
//! provider, not about the turn: two engine processes reading two frame streams at once would
//! interleave their logs into one another's output and reach the provider with two requests in the
//! same instant.
//!
//! The items the other modules reach are `pub`; `PROVIDER_CONFIG` and `WRAPPER` stay private to the
//! launch that plants them.

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::Duration;

use agent_client_protocol::schema::v1::{
    RequestPermissionOutcome, RequestPermissionResponse, SelectedPermissionOutcome,
};
use nekowite_lib::agent_runtime::{
    env_pairs, isolated_profile_env, EngineConnection, EngineLaunch, FsRequest, PermissionRequest,
    SYSTEM_CA_BUNDLE,
};
use tokio::sync::mpsc::UnboundedReceiver;

/// The artifact P0 §1 pins, gitignored and a pipeline product — the same path every other live
/// target names.
const ARTIFACT: &str = "binaries/opencode-x86_64-unknown-linux-gnu";

/// The model the other live targets use, and the same gateway. Not a default this app ships.
pub const TEST_MODEL: &str = "iapp/deepseek-v4-flash";

/// How long one turn may take. The other live targets allow 150s for the same reason.
pub const RUN_PATIENCE: Duration = Duration::from_secs(150);

/// How long a control call may take. `session/new` and `session/list` reach no provider.
pub const CALL_BOUND: Duration = Duration::from_secs(60);

/// The profile's provider block, byte for byte the one `agent_live_test.rs` and the replay target
/// use. The credential is an `{env:…}` reference, so it exists in no file this test writes.
const PROVIDER_CONFIG: &str = r#"{
  "provider": {
    "iapp": {
      "npm": "@ai-sdk/openai-compatible",
      "name": "iApp Gateway (test)",
      "options": {
        "baseURL": "https://ai.iapp.dpdns.org/v1",
        "apiKey": "{env:NWK_TEST_KEY}"
      },
      "models": {
        "deepseek-v4-flash": { "name": "DeepSeek V4 Flash" }
      }
    }
  }
}
"#;

/// The wrapper the launch goes through.
///
/// Two `tee`s and no other change: the engine is still the program that runs, on the same pipes,
/// with the same environment, in the same process group. What is added is a copy of each direction
/// on disk. `set -o pipefail` so the wrapper's status is the engine's rather than the last
/// `tee`'s, and `exec` is deliberately not used — the second `tee` has to outlive the engine to
/// flush what the engine wrote last.
const WRAPPER: &str = r#"#!/usr/bin/env bash
# Generated by tests/agent_wire_frames_live_test.rs. Records both directions of the ACP
# conversation, then hands the engine's stdio straight back to the caller.
set -uo pipefail
"$NWK_WIRE_ENGINE" "$@" \
  < <(tee -a "$NWK_WIRE_DIR/to-engine.jsonl") \
  | tee -a "$NWK_WIRE_DIR/from-engine.jsonl"
"#;

/// One live connection, in the two halves a caller needs.
pub struct Live {
    pub connection: Arc<EngineConnection>,
    pub updates: UnboundedReceiver<agent_client_protocol::schema::v1::SessionNotification>,
    pub permissions: UnboundedReceiver<PermissionRequest>,
    pub fs: UnboundedReceiver<FsRequest>,
    pub wire: PathBuf,
}

pub fn scratch(label: &str) -> PathBuf {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("target/acp-wire-frames")
        .join(format!("{label}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("scratch dir");
    dir
}

/// The engine, or a printed skip — the same guard every live target uses.
pub fn artifact() -> Option<PathBuf> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(ARTIFACT);
    if path.is_file() {
        return Some(path);
    }
    eprintln!(
        "SKIP: {} is absent; run scripts/fetch-opencode-linux.sh",
        path.display()
    );
    None
}

/// The engine **and** the credential, or a printed skip — what the paying test needs.
///
/// The same two CA conditions `agent_live_test.rs` applies, for the reason that file states: they
/// are what make a successful prompt evidence about the runtime's own CA injection rather than
/// about an environment that already had one.
pub fn live_run_inputs() -> Option<(PathBuf, String)> {
    let artifact = artifact()?;
    if std::env::var_os("NODE_EXTRA_CA_CERTS").is_some() {
        eprintln!(
            "SKIP: NODE_EXTRA_CA_CERTS is already set, so this would not be evidence about the \
             runtime's own CA injection"
        );
        return None;
    }
    if !Path::new(SYSTEM_CA_BUNDLE).is_file() {
        eprintln!("SKIP: {SYSTEM_CA_BUNDLE} is absent, so the prompt could not succeed");
        return None;
    }
    match std::env::var("NWK_TEST_KEY") {
        Ok(key) if !key.trim().is_empty() => Some((artifact, key)),
        _ => {
            eprintln!(
                "SKIP: NWK_TEST_KEY is not set; scripts/verify-acp-live.sh is what exports it from \
                 /tmp/nkw-test-key"
            );
            None
        }
    }
}

/// Starts the engine with the wrapper round it, and the profile's provider config planted.
pub async fn start(artifact: &Path, key: &str, root: &Path) -> Live {
    let profile = root.join("profile");
    let config_dir = profile.join("XDG_CONFIG_HOME/opencode");
    fs::create_dir_all(&config_dir).expect("profile config dir");
    fs::write(config_dir.join("opencode.json"), PROVIDER_CONFIG).expect("provider config");
    let wire = root.join("wire");
    fs::create_dir_all(&wire).expect("wire dir");

    let script = wire.join("launch.sh");
    fs::write(&script, WRAPPER).expect("wrapper script");
    fs::set_permissions(&script, fs::Permissions::from_mode(0o755)).expect("wrapper mode");

    let mut env = isolated_profile_env(&profile);
    env.push(("NWK_TEST_KEY".to_string(), key.to_string()));
    env.push((
        "NWK_WIRE_ENGINE".to_string(),
        artifact.to_string_lossy().into_owned(),
    ));
    env.push((
        "NWK_WIRE_DIR".to_string(),
        wire.to_string_lossy().into_owned(),
    ));
    let launch = EngineLaunch {
        program: script,
        args: vec!["acp".to_string()],
        env: env_pairs(env),
        ca_bundle: None,
    };

    let (connection, events) = EngineConnection::connect(&launch)
        .await
        .expect("the real engine should start behind the wrapper");
    Live {
        connection: Arc::new(connection),
        updates: events.updates,
        permissions: events.permissions,
        fs: events.fs,
        wire,
    }
}

/// Answers the reverse requests, so a turn can never hang on one.
///
/// Neither is expected to carry anything — the pinned engine's default configuration asks for
/// nothing (P0 §4 and §7 measured it) — and each request that does arrive is printed, because an
/// unexpected one is a measurement rather than an inconvenience.
pub fn servant(
    mut permissions: UnboundedReceiver<PermissionRequest>,
    mut fs: UnboundedReceiver<FsRequest>,
) -> tokio::task::JoinHandle<()> {
    tokio::spawn(async move {
        loop {
            tokio::select! {
                permission = permissions.recv() => match permission {
                    Some(request) => {
                        // The engine's own option ids, in the engine's own order: the first is the
                        // least surprising answer a probe with no user can give, and it is the
                        // engine's id rather than one this side invented (§6.3).
                        let option = request
                            .request
                            .options
                            .first()
                            .map(|option| option.option_id.clone());
                        eprintln!(
                            "  !! the engine asked for permission on {:?} — answering {:?}",
                            request.request.tool_call.fields.title, option
                        );
                        if let Some(option_id) = option {
                            let _ = request.responder.respond(RequestPermissionResponse::new(
                                RequestPermissionOutcome::Selected(
                                    SelectedPermissionOutcome::new(option_id),
                                ),
                            ));
                        } else {
                            let _ = request
                                .responder
                                .respond_with_internal_error("the engine offered no option");
                        }
                    }
                    None => break,
                },
                fs = fs.recv() => match fs {
                    Some(request) => {
                        eprintln!("  !! the engine delegated a file request to the host");
                        request.refuse_with(agent_client_protocol::Error::internal_error().data(
                            "a wire probe serves no vault",
                        ));
                    }
                    // The update stream outlives this one only if the connection dies; either way
                    // there is nothing left to answer.
                    None => return,
                },
            }
        }
        while let Some(request) = fs.recv().await {
            request
                .refuse_with(agent_client_protocol::Error::internal_error().data("probe closed"));
        }
    })
}

/// One turn at a time, across every test in this target.
///
/// `cargo test` runs a target's tests in parallel by default, and two engine processes reading two
/// frame streams at once would interleave their logs into one another's output and reach the
/// provider with two requests in the same instant. Serialized, the log of a run is that run's.
pub fn one_turn_at_a_time() -> &'static tokio::sync::Mutex<()> {
    static LOCK: std::sync::OnceLock<tokio::sync::Mutex<()>> = std::sync::OnceLock::new();
    LOCK.get_or_init(|| tokio::sync::Mutex::new(()))
}

/// A receiver that is already closed, for a channel this run has handed to someone else.
pub fn unused<T>() -> UnboundedReceiver<T> {
    let (sender, receiver) = tokio::sync::mpsc::unbounded_channel();
    drop(sender);
    receiver
}
